window.__freeMovies__ = [
  {
    id: 1,
    filmName: "A Tower on the Mountain",
    filmDesc: "Documentary | 51 min ",
    introduction: "The archetecture of Ernest Cormier and his life with Clorinthe Perron.",
    filmImgPath: "https://smart-java-prod.smartcinemausa.com/trailer/1614940086609_W5zdr.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/3cf326368c22454b9ff46604127d7dad-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_ATowerontheMountain.mp4"
  },
  {
    id: 2,
    filmName: "COMING HOME : BEYOND A MOONLESS NIGHT",
    filmDesc: "Documentary | 92 min",
    introduction: "Forty years after having fled the war in Vietnam through Laos, a young Canadian woman who arrived as a Boat People refugee goes back to her native land to meet with a long lost aunt. The emotional gathering sets the tone for a discovery trip and identity quest across Vietnam but also Lao and Cambodia, the three countries that once comprised French Indochina. By interviewing common people with extraordinary lives, the film draws links between the eruption of the war and decades of colonization.",
    filmImgPath: "https://g.smartcinemausa.com/images/1d82b14f04614d999bd4569cd6fd1f1a-700-1000.jpg",
    filmScore: 4.8,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/a11a5ebff4974fdabc365c901952242e-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_Coming_Home_Beyond_a_Moonless_Night_mix20TV_HD_23976p.mp4"
  },
  {
    id: 3,
    filmName: "Journey to the East",
    filmDesc: "Documentary | 12 min",
    introduction: "A doucmentary on the history and life of Canadian international students in China.",
    filmImgPath: "https://g.smartcinemausa.com/images/152045fca60b4da5acf2cb10a49da5e9-700-1000.jpg",
    filmScore: 4.8,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/a2b22dab2d854c8faa2b8fd5585ccfc2-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_加拿大留学生在中国.mp4"
  },
  {
    id: 4,
    filmName: "Innocent",
    filmDesc: "Comedy | 90 min",
    introduction: "Francis is a nice, ordinary guy with a propensity to get into trouble in spite of himself: a dispute with his brother-in-law over a winning lottery ticket; a conflict with a wanted criminal over funeral urns; attempts to aid his elderly neighbour, his new tenant, and the ex he is still in love with, every time with unexpected (and certainly not positive) consequences.",
    filmImgPath: "https://g.smartcinemausa.com/images/4938fa6c363b4d33a861830b0234c8c1-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/e5de2398757347359b90a514d798bf84-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_INNOCENT.mp4"
  },
  {
    id: 5,
    filmName: "My Dear Liar",
    filmDesc: "Drama/Comedy | 112 min",
    introduction: "In order to rescue his 6 years old son who is suffering from asthma with his friend Zhong Zhenjiang (Zhang Zixian)’s incitement, Wuhai (Da Peng) gets close to a low class Cam girl Miaomiao (Liu Yan) on purpose. And he determines to trap her into a marriage scam.",
    filmImgPath: "https://g.smartcinemausa.com/images/7bfee3f7d41f4526bc6e577fea376a65-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/066663b8ba3547b8a6bb2b707e99d9dc-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_SYR_sub_HD_Sound20_DVD_proxy.mp4"
  },
  {
    id: 6,
    filmName: "Highway to Heaven",
    filmDesc: "Documentary | 16 min",
    introduction: "This short symphonic documentary offers a glimpse into the unique religious co-existence found along No. 5 Road in Richmond, British Columbia. Highway to Heaven takes audiences into many of the temples, mosques, and churches that call No. 5 home, revealing unity despite difference across these diverse cultural spaces. In a world struggling with religious violence and intolerance, filmmaker Sandra Ignagni has crafted a gentle portrait of a rare landscape using attentive imagery and an acoustic tapestry of prayer.",
    filmImgPath: "https://smart-java-prod.smartcinemausa.com/trailer/1614848725292_BQjpn.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/314a622a501c48e381f648b26e33715f-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_HighwayToHeaven_NFB_Projection.mp4"
  },
  {
    id: 7,
    filmName: "Old Dog",
    filmDesc: "Animation | 3 min",
    introduction: "After losing his best friend, an elderly pug named Henry must depend on his owner for help and companionship. Writer/director Ann Marie Fleming (Window Horses) makes visible the tender work of caretaking in her new animated short, Old Dog. All dogs (and people) should be so lucky and so loved.",
    filmImgPath: "https://smart-java-prod.smartcinemausa.com/trailer/1614847612628_DKzrR.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/702afc62c5ff48e8a7220b4e47e22096-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_OldDog.mp4"
  },
  {
    id: 8,
    filmName: "The Farewell",
    filmDesc: "Drama | 98 min",
    introduction: "A headstrong Chinese-American woman returns to China when her beloved grandmother is diagnosed with terminal cancer. Billi struggles with her family's decision to keep grandma in the dark about her own illness as they all stage an impromptu wedding to see grandma one last time.",
    filmImgPath: "https://smart-java-prod.smartcinemausa.com/trailer/1614850099205_a2PMS.jpg",
    filmScore: 4.8,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/1c365468451b4d45b0092cf0de854042-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_BGST.mp4"
  },
  {
    id: 9,
    filmName: "The Front Line",
    filmDesc: "Documentary | 90 min",
    introduction: "The documentary truly recorded the real state of Wuhan in the epidemic in more than 50 days after the outbreak. There were doctors from the national emergency rescue team, who fight for life with death in the front line day and night; there are temporary shelter hospitals, in which thousands of patients share their life and emotions; there are moving stories of ordinary people who become volunteers who rush to rescue and do good deeds; there are ordinary people who live in isolation and show their tenacity in self-restraint...",
    filmImgPath: "https://smart-java-prod.smartcinemausa.com/trailer/1615175463089_JrjRs.jpg",
    filmScore: 4.8,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/ebb2833f4cfe486b931d22efb7785582-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_第一线合集.mp4"
  },
  {
    id: 10,
    filmName: "The Stone and the Sea",
    filmDesc: "Animation | 9 min",
    introduction: "An animated story of ancient Chinese mythology.",
    filmImgPath: "https://smart-java-prod.smartcinemausa.com/trailer/1615173648993_dEXW7.jpg",
    filmScore: 4.8,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/e6e5c879a8ab4347b38293e748d0f261-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_填海记.mp4"
  },
  {
    id: 11,
    filmName: "Through the Seasons",
    filmDesc: "Documentary | 30 min",
    introduction: "Award winning documentary on beatifful Xinjiang through four seasons.",
    filmImgPath: "https://g.smartcinemausa.com/images/4afaad205b5b4149bd7e866f0dcbb1a5-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/0b52bcb4437f4c2f90d11394cd60ff4d-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_走过四季.mp4"
  },
  {
    id: 12,
    filmName: "Wilcox",
    filmDesc: "Documentary | 66 min",
    introduction: "A mysterious drifter who exists outside the norm heads into the woods alone in an apparent quest for adventure.",
    filmImgPath: "https://g.smartcinemausa.com/images/3ac2ef0414cc4c20bf1931d3114adf15-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/37a17474bf2b46f8a12f106e0981fad5-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_WILCOX.mp4"
  },
  {
    id: 13,
    filmName: "Born in 2000",
    filmDesc: "Documentary | 89 min",
    introduction: "The documentary was filmed over 12 years. Since 2006, the Documentary Center of Beijing Normal University has been recording the lives of a dozen children born after 2000 from kindergarten to middle school.The film is based on two of them, Chi Yiyang and Rourou. Chi Yiyang wanted to be a hero from a young age and was very naughty. After struggling to find his way, he found direction through the sport of rugby. Rourou, who dreamt of becoming a princess, encountered unprecedented setbacks after going to study in the United States. The film, by exploring such topics as exam-oriented education, staying behind and studying abroad, presents an honest look at China's education system and the choices faced by Chinese parents.",
    filmImgPath: "https://g.smartcinemausa.com/images/8d5ba2865be040b4b0814e829b9d573a-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/af2d5d362a6a4368b72d9329067374b8-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_零零后.mp4"
  },
  {
    id: 14,
    filmName: "Night Watch",
    filmDesc: "Thriller | 85 min",
    introduction: "A midnight car accident took away a young girl's life. Her companion Jie became the sole survivor of the accident but was haunted by the ghost of the girl ever since. With the help of his therapist Hong, Jie found a night watch job at a deserted building. When the ghost meets another ghost in the house, is it karma or curse?",
    filmImgPath: "https://g.smartcinemausa.com/images/469e4e1807ab4549b5aee47cd233df04-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/9d895fcc1c234b4b8c4db3d55068db46-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_夜守.mp4"
  },
  {
    id: 15,
    filmName: "The Man Standing Next",
    filmDesc: "Drama/Thriller | 114 min",
    introduction: "In the 1970s, Korea is under the absolute control of President Park who controls the KCIA, the organization with an edge over any branch of government. The director of the KCIA, Kim Gyu-pyeong, is nearly the second-in-command, but faces rivalry from the president's security chief. In the midst of a reign of fear, a former KCIA director, Park Yong-gak, who knows all about the government's obscure and illegal operations, goes into exile, and testifies in front of the U.S. Congress, opening the floodgates to the investigation of Koreagate. As tension escalates, stifling political maneuvers by those desiring power collide explosively.",
    filmImgPath: "https://g.smartcinemausa.com/images/1c2767a00cd64d7f8f0997138fe00028-956-1365.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/1a41002693434e519a9ecd44afcf9053-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_南山的部长们.mp4"
  },
  {
    id: 16,
    filmName: "Bridge of Destiny",
    filmDesc: "Action | 91 min",
    introduction: "Just another love story when she loves him, while he loves him.",
    filmImgPath: "https://g.smartcinemausa.com/images/89ad9afed0774a638ac397c3308bfc83-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/9c7c20a4c0da46049217e9f5caeae0b0-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_BridgeOfDestiny_XX_20_51_ME20_ME51_Skyline.mp4"
  },
  {
    id: 17,
    filmName: "Furie",
    filmDesc: "Action | 98 min",
    introduction: "FURIE follows Hai Phuong, a gangster who retired from the life of crime after the birth of her daughter. Despite lying low in the countryside, she can’t seem to escape her violent past when her daughter is kidnapped right before her eyes. Hai Phuong is forced back into the life she swore she would leave behind and will stop at nothing to get her daughter back from the infamous organ-trafficking ring.",
    filmImgPath: "https://g.smartcinemausa.com/images/500f5afae4e842d9860bf3d733505f05-974-1392.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/0eb5a35dfc124063910b32caf3dfc29b-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_WellGo_Furie_Feature.mp4"
  },
  {
    id: 18,
    filmName: "Mrs.Sun",
    filmDesc: "Drama | 9 min",
    introduction: "Li Chen has a strict teacher in high school-Mrs. Sun, who punishes her students physically and mentally. After a closer contact with Mrs. Sun, Li Chen found out that Mrs.Sun has a much more layered personality than she looked like.",
    filmImgPath: "https://g.smartcinemausa.com/images/989df7f114ab46c1a9de00783349a221-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/1faef077a3114c0a980e11505516906d-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_彩华9分钟.mp4"
  },
  {
    id: 19,
    filmName: "THE MAN IN THE SUIT",
    filmDesc: "Drama | 30 min",
    introduction: "Beijing floater Li put all his hope in his post graduate entrance exam. He saw it as his gateway to change his life in predicament. Li worked as a realtor in a real estate agency to support his dream, where his new colleague, a post graduate, told him everything about the exam that shattered his dream and hope.",
    filmImgPath: "https://g.smartcinemausa.com/images/9a815a35c357493194556cf8d6a1f3b6-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/c96489ca36084282b12cb03590d170c3-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_床太软了.mp4"
  },
  {
    id: 20,
    filmName: "CHORUS",
    filmDesc: "Drama | 15 min",
    introduction: "A campus chorus competition is about to begin. For FangXiang, a sixth-grade girl who is about to graduate, her otherwise plain life has set off a small storm. After inferiority to self-confidence, after choosing and making choices, it is growth and youth for others...",
    filmImgPath: "https://g.smartcinemausa.com/images/aaca80a89a3746fb9ea71c1f2b953d9c-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/e27f6af45a1b45ff96f53c4a36704a11-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_合唱.mp4"
  },
  {
    id: 21,
    filmName: "The Blackhole",
    filmDesc: "Drama | 30 min",
    introduction: "The film begins with a Buddha statue and a face gazing at it. Xiaoshuan's uncle dies. He returns to his childhood home to find out the truth of his uncle's death in the cold winter. The middle-aged people who drink too much, the young people who collect debts and the mysterious tramps tell us a random life segment.",
    filmImgPath: "https://g.smartcinemausa.com/images/3192b22f302f4a2b84d03e894a377342-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/4b01d6c1faf14db49ee008517290eaa9-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_黑洞.mp4"
  },
  {
    id: 22,
    filmName: "Then She Went On Stage",
    filmDesc: "Drama | 17 min",
    introduction: "Luo Nan, a seventh-grade girl, goes to the variety store every day to take one piece of newspaper with a blue note stuck on, which is the way her sick mom and the shopkeeper having an affair. With her mom’s life counting down, Nan is no longer able to ignore the fact that her parents do not love each other anymore. She uses her special way to encourage her mom to leave the family. ",
    filmImgPath: "https://g.smartcinemausa.com/images/f0928b4102eb40a4841b385cf5416fb5-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/2e0c44facda24262a2309dbb362ea857-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_罗南的演讲_正片.mp4"
  },
  {
    id: 23,
    filmName: "HEADING NOWHERE",
    filmDesc: "Drama | 40 min",
    introduction: "In June 2020, I went back to my hometown and began to re-prepare \"NOWHERE TO ENCOUNTER\", which was forced to be shelved after the outbreak of the Covid-19 at the beginning of the year. \"NOWHERE TO ENCOUNTER\" tells the story of a man Linlu ，who has just returned after a six-year prison sentence. At the end of the film, a miracle happens to the man whose faith has collapsed，he met his grandmother who has passed away.",
    filmImgPath: "https://g.smartcinemausa.com/images/99244e7ffb5f4d0daac573500a76684e-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/1dc45062ca1f4e0faad22d7f898ba48c-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_再见牛圈.mp4"
  },
  {
    id: 24,
    filmName: "Begonia",
    filmDesc: "Drama | 5 min",
    introduction: "Two girls are waiting in the living room because their friends are quarreling next door. They seem like don't know each other very well so they don't have much to talk about, As the conversation goes on, reveals their unforgettable past.",
    filmImgPath: "https://g.smartcinemausa.com/images/34d10bf252ef415d8aa6fff0841ddb39-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/8665d09ff73646089df5336e1c9f86e8-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_果果5分钟.mp4"
  },
  {
    id: 25,
    filmName: "Fist and Furious",
    filmDesc: "Drama | 90 min",
    introduction: "A North Korean defector, Gook Hyeon has made a new life for himself in South Korea, working as a freelance video journalist. Always on the hunt for a compelling story to cover, he’s only interested in working on the most provocative pieces.",
    filmImgPath: "https://g.smartcinemausa.com/images/da0c500c437640c088692f65316ec3da-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/e1fbfa5fc4a943d5afdf738873d21bab-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_Fist_and_Furious.mp4"
  },
  {
    id: 26,
    filmName: "The Pick-up Artist",
    filmDesc: "Drama | 97 min",
    introduction: "Chen Junfei, known as the empathy master, and his colleagues attempt to help married couples solve their emotional problems. In order to assist a beautiful new client named Shan Zhuo, Chen Junfei personally disguises himself as a fortune-teller. However, Chen Junfei quickly realises that this latest job won’t be as easy as he initially expected",
    filmImgPath: "https://g.smartcinemausa.com/images/b683139d76ba44dcb56e9a9c4f49d27a-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/180aada14fb1443c895ba32342d253c7-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_移情高手.mp4"
  },
  {
    id: 27,
    filmName: "Vortex",
    filmDesc: "Drama | 103 min",
    introduction: "LIU is in desperate need of money after losing at gambling, again. A friend can help, he just needs to steal an unregistered car back and resell it. The simple scam becomes complicated when they find a little girl in the trunk of the car.",
    filmImgPath: "https://g.smartcinemausa.com/images/6e06f790047e4128a6ea14472b21e1a1-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/2bdb9fb68f6f4e43b0dcf2de1e92d6fd-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_铤而走险.mp4"
  },
  {
    id: 28,
    filmName: "Chronology",
    filmDesc: "Drama | 117 min",
    introduction: "Hakan and Nihal have been married for many years. Shortly after they find out that Nihal is unable to have children, she disappears. While frantically searching for her, Hakan makes some painful discoveries about himself and their marriage. He must face his inner demons to discover what happened to his wife.",
    filmImgPath: "https://g.smartcinemausa.com/images/dba46eaf6f6649b580e6cc06c64ba13b-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/b64fa723f7b94e1d9002e4fb97d8d42d-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_Chronology.mp4"
  },
  {
    id: 29,
    filmName: "Siren's Call",
    filmDesc: "Drama | 93 min",
    introduction: "Welcome to the New Istanbul! A massive concrete jungle feeding on chaos and hypocrisy; it's inhabitants at the end of their tether.",
    filmImgPath: "https://g.smartcinemausa.com/images/27e5277410184653bc700b47c8532d66-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/4340a80e7ca74d589afa2b39b390d7c1-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_Sirens_Call.mp4"
  },
  {
    id: 30,
    filmName: "Steel Rain 2: Summit",
    filmDesc: "Drama | 132 min",
    introduction: "A summit of leaders of South Korea, North Korea and the U.S., where they intend to discuss North Korea's nuclear issue and a peace settlement for the Korean peninsula, but instead end up being abducted.",
    filmImgPath: "https://g.smartcinemausa.com/images/d763bd14bf9849a8a1912e91ca8367f1-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/b79d78bda4254c6f9a5d836ca904a449-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_Steel_Rain2.mp4"
  },
  {
    id: 31,
    filmName: "Jade Dynasty",
    filmDesc: "Drama | 101 min",
    introduction: "ZHANG Xiaofan is an orphan, his parents been murdered by enemies and he became a member in Green Justic League, met and fell in love with Biyao. One day he knew the truth behind his parents' death and ran out from the League to save himself, Biyao saved him but fell into a coma forever...",
    filmImgPath: "https://g.smartcinemausa.com/images/c63edd41f23749509ed7a3f36b7c2862-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinema.com.cn/images/9c359d2499c041df848d42c871da69b7-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_诛仙.mp4"
  },
  {
    id: 32,
    filmName: "The Story of Hay Bo",
    filmDesc: "Drama | 112 min",
    introduction: "Jiang Xi Bao, a student at an elite college while under distressed circumstances. By chance, she meets Xu Cong Hui, the daughter of the distinguished and affluent Xu family. As the two girls become close friends, Xi Bao eventually encounters Cong Hui's father, Mr. Xu Cun Zi. What initially began as a trade of her youth in exchange for material pleasure, develops into a romance, the relationship between Xi Bao and Mr. Xu deepens.",
    filmImgPath: "https://g.smartcinemausa.com/images/32a7c2399da240438c0a1192863fb28f-700-1000.jpg",
    filmScore: 4.9,
    scoreScaleList: [0.9, 0.1, 0, 0, 0],
    filmPoster: "https://g.smartcinemausa.com/images/1745179335f8486a97c2f176fa5b15f5-1125-633.jpg",
    filmSource: "http://aws-smart-prod-dash.smartcinemausa.com/CandaChine/new/pre_喜宝.mp4"
  }
]
